In [1343]:
import pandas as pd
import numpy as np
from scipy.fft import fft

In [1344]:
df = pd.read_csv('C:/Users/saraa/OneDrive/Desktop/CDSS - Final Project/data/csv files/merged_files.csv')

In [1345]:
df

,time,channel1,channel2,channel3,channel4,channel5,channel6,channel7,channel8,class,label
0,1,0.00001,-0.00002,-0.00001,-0.00003,0.00000,-0.00001,0.00000,-0.00001,0,1
1,5,0.00001,-0.00002,-0.00001,-0.00003,0.00000,-0.00001,0.00000,-0.00001,0,1
2,6,-0.00001,0.00001,0.00002,0.00000,0.00001,-0.00002,-0.00001,0.00001,0,1
3,7,-0.00001,0.00001,0.00002,0.00000,0.00001,-0.00002,-0.00001,0.00001,0,1
4,8,-0.00001,0.00001,0.00002,0.00000,0.00001,-0.00002,-0.00001,0.00001,0,1
...,...,...,...,...,...,...,...,...,...,...,...
4237902,50962,0.00001,-0.00001,-0.00002,-0.00004,-0.00012,0.00000,0.00002,0.00002,0,36
4237903,50963,0.00001,-0.00001,-0.00002,-0.00004,-0.00012,0.00000,0.00002,0.00002,0,36
4237904,50964,0.00001,-0.00001,-0.00002,-0.00004,-0.00012,0.00000,0.00002,0.00002,0,36
4237905,50965,0.00001,-0.00001,-0.00002,-0.00004,-0.00012,0.00000,0.00002,0.00002,0,36
4237906,50966,0.00001,-0.00001,-0.00002,-0.00004,-0.00012,0.00000,0.00002,0.00002,0,36

In [1346]:
df['class'].value_counts()

0    2725157
6     253009
5     251733
4     251570
1     250055
3     249494
2     243193
7      13696
Name: class, dtype: int64

In [1347]:
index_numbers_1 = df[df["class"] == 0].index 
df.drop(index_numbers_1, inplace=True)

In [1348]:
df['class'].value_counts()

6    253009
5    251733
4    251570
1    250055
3    249494
2    243193
7     13696
Name: class, dtype: int64

In [1349]:
index_numbers_2 = df[df["class"] == 7].index
df.drop(index_numbers_2, inplace=True)

In [1350]:
df['class'].value_counts()

6    253009
5    251733
4    251570
1    250055
3    249494
2    243193
Name: class, dtype: int64

In [1351]:
df = df.drop(['time'], axis=1)

In [1352]:
df = df.groupby(['label','class'])

In [1353]:
df.get_group((1,1))

,channel1,channel2,channel3,channel4,channel5,channel6,channel7,channel8,class,label
2287,-0.00001,0.00000,-0.00001,0.00000,0.00000,-0.00001,-0.00001,0.00001,1,1
2288,-0.00001,-0.00002,0.00000,-0.00001,-0.00001,-0.00001,-0.00003,-0.00002,1,1
2289,-0.00001,-0.00002,0.00000,-0.00001,-0.00001,-0.00001,-0.00003,-0.00002,1,1
2290,-0.00001,-0.00002,0.00000,-0.00001,-0.00001,-0.00001,-0.00003,-0.00002,1,1
2291,-0.00001,-0.00002,0.00000,-0.00001,-0.00001,-0.00001,-0.00003,-0.00002,1,1
...,...,...,...,...,...,...,...,...,...,...
94903,-0.00001,-0.00001,-0.00003,-0.00001,0.00000,0.00001,-0.00001,0.00000,1,1
94904,-0.00001,-0.00001,-0.00003,-0.00001,0.00000,0.00001,-0.00001,0.00000,1,1
94905,-0.00001,-0.00001,-0.00003,-0.00001,0.00000,0.00001,-0.00001,0.00000,1,1
94906,-0.00001,-0.00001,-0.00003,-0.00001,0.00000,0.00001,-0.00001,0.00000,1,1
94907,0.00001,0.00003,0.00004,0.00006,0.00002,0.00002,-0.00001,0.00002,1,1

In [1354]:
def IEMG(data):
    return np.sum(np.abs(data), axis=0)

def SSI(data):
    return np.sum(data**2, axis=0)

def rms(data):
      return  np.sqrt(np.mean(data**2, axis=0))

def MAV(data):
    return np.mean(np.abs(data), axis=0)

def variance(data):
    return np.var(data, axis=0)

def WL(data):
    return np.sum(np.abs(np.diff(data,axis=0)),axis = 0)

def DAMV(data):
    return np.mean(np.abs(np.diff(data, axis=0)), axis=0)

def DASDV(data):
    return np.std(np.abs(np.diff(data, axis=0)), axis=0)

def WAMP(data):
    differences = np.abs(np.diff(data, axis=0))
    threshold = np.mean(np.mean(differences, axis=0))
    return np.sum(differences > threshold, axis=0)

In [1355]:
df = df.agg(['min','max',IEMG,SSI,rms,MAV,variance,WL,np.ptp,DAMV,DASDV,WAMP])

In [1356]:
df = df.reset_index()
df

    label class channel1                                                  \
                     min      max     IEMG       SSI       rms       MAV
0       1     1 -0.00005  0.00004  0.09206  0.000002  0.000017  0.000013
1       1     2 -0.00111  0.00095  1.08119  0.000301  0.000210  0.000159
2       1     3 -0.00087  0.00112  1.01219  0.000260  0.000188  0.000138
3       1     4 -0.00020  0.00016  0.27419  0.000022  0.000056  0.000040
4       1     5 -0.00031  0.00061  0.32088  0.000030  0.000066  0.000045
..    ...   ...      ...      ...      ...       ...       ...       ...
211    36     2 -0.00128  0.00119  1.68831  0.000788  0.000360  0.000277
212    36     3 -0.00077  0.00067  0.84687  0.000204  0.000183  0.000139
213    36     4 -0.00014  0.00017  0.22486  0.000015  0.000050  0.000038
214    36     5 -0.00059  0.00042  0.51000  0.000091  0.000126  0.000089
215    36     6 -0.00047  0.00045  0.45388  0.000073  0.000110  0.000076

                            ... channel8                                \
         variance       WL  ...     IEMG       SSI       rms       MAV
0    1.963786e-10  0.01070  ...  0.07895  0.000001  0.000014  0.000011
1    4.407886e-08  0.16819  ...  0.77213  0.000153  0.000150  0.000113
2    3.535269e-08  0.14544  ...  0.88888  0.000190  0.000161  0.000121
3    3.033667e-09  0.03609  ...  0.40173  0.000047  0.000083  0.000059
4    4.212237e-09  0.04939  ...  0.30658  0.000025  0.000060  0.000043
..            ...      ...  ...      ...       ...       ...       ...
211  1.291361e-07  0.28640  ...  0.88827  0.000214  0.000187  0.000146
212  3.362221e-08  0.13963  ...  0.41009  0.000050  0.000091  0.000067
213  2.407232e-09  0.03460  ...  0.24908  0.000018  0.000055  0.000042
214  1.576481e-08  0.08415  ...  0.13197  0.000006  0.000031  0.000023
215  1.210762e-08  0.07699  ...  0.54380  0.000093  0.000124  0.000091


         variance       WL      ptp      DAMV     DASDV WAMP
0    1.233863e-10  0.00921  0.00007  0.000001  0.000005  530
1    2.223041e-08  0.11696  0.00124  0.000017  0.000067  660
2    2.589898e-08  0.11869  0.00124  0.000016  0.000066  660
3    6.620592e-09  0.04984  0.00058  0.000007  0.000030  619
4    3.496563e-09  0.04606  0.00075  0.000007  0.000027  675
..            ...      ...      ...       ...       ...  ...
211  3.484948e-08  0.13880  0.00134  0.000023  0.000086  623
212  8.186731e-09  0.06638  0.00072  0.000011  0.000042  566
213  3.026806e-09  0.03878  0.00035  0.000007  0.000025  591
214  9.112373e-10  0.02195  0.00024  0.000004  0.000014  580
215  1.545373e-08  0.09120  0.00098  0.000015  0.000059  621

[216 rows x 98 columns]

In [1357]:
df.to_csv('features.csv')

In [1358]:
df['channel1']['min']

0     -0.00005
1     -0.00111
2     -0.00087
3     -0.00020
4     -0.00031
        ...
211   -0.00128
212   -0.00077
213   -0.00014
214   -0.00059
215   -0.00047
Name: min, Length: 216, dtype: float64

In [1359]:
df.columns

MultiIndex([(   'label',         ''),
            (   'class',         ''),
            ('channel1',      'min'),
            ('channel1',      'max'),
            ('channel1',     'IEMG'),
            ('channel1',      'SSI'),
            ('channel1',      'rms'),
            ('channel1',      'MAV'),
            ('channel1', 'variance'),
            ('channel1',       'WL'),
            ('channel1',      'ptp'),
            ('channel1',     'DAMV'),
            ('channel1',    'DASDV'),
            ('channel1',     'WAMP'),
            ('channel2',      'min'),
            ('channel2',      'max'),
            ('channel2',     'IEMG'),
            ('channel2',      'SSI'),
            ('channel2',      'rms'),
            ('channel2',      'MAV'),
            ('channel2', 'variance'),
            ('channel2',       'WL'),
            ('channel2',      'ptp'),
            ('channel2',     'DAMV'),
            ('channel2',    'DASDV'),
            ('channel2',     'WAMP'),
            ('channel3',      'min'),
            ('channel3',      'max'),
            ('channel3',     'IEMG'),
            ('channel3',      'SSI'),
            ('channel3',      'rms'),
            ('channel3',      'MAV'),
            ('channel3', 'variance'),
            ('channel3',       'WL'),
            ('channel3',      'ptp'),
            ('channel3',     'DAMV'),
            ('channel3',    'DASDV'),
            ('channel3',     'WAMP'),
            ('channel4',      'min'),
            ('channel4',      'max'),
            ('channel4',     'IEMG'),
            ('channel4',      'SSI'),
            ('channel4',      'rms'),
            ('channel4',      'MAV'),
            ('channel4', 'variance'),
            ('channel4',       'WL'),
            ('channel4',      'ptp'),
            ('channel4',     'DAMV'),
            ('channel4',    'DASDV'),
            ('channel4',     'WAMP'),
            ('channel5',      'min'),
            ('channel5',      'max'),
            ('channel5',     'IEMG'),
            ('channel5',      'SSI'),
            ('channel5',      'rms'),
            ('channel5',      'MAV'),
            ('channel5', 'variance'),
            ('channel5',       'WL'),
            ('channel5',      'ptp'),
            ('channel5',     'DAMV'),
            ('channel5',    'DASDV'),
            ('channel5',     'WAMP'),
            ('channel6',      'min'),
            ('channel6',      'max'),
            ('channel6',     'IEMG'),
            ('channel6',      'SSI'),
            ('channel6',      'rms'),
            ('channel6',      'MAV'),
            ('channel6', 'variance'),
            ('channel6',       'WL'),
            ('channel6',      'ptp'),
            ('channel6',     'DAMV'),
            ('channel6',    'DASDV'),
            ('channel6',     'WAMP'),
            ('channel7',      'min'),
            ('channel7',      'max'),
            ('channel7',     'IEMG'),
            ('channel7',      'SSI'),
            ('channel7',      'rms'),
            ('channel7',      'MAV'),
            ('channel7', 'variance'),
            ('channel7',       'WL'),
            ('channel7',      'ptp'),
            ('channel7',     'DAMV'),
            ('channel7',    'DASDV'),
            ('channel7',     'WAMP'),
            ('channel8',      'min'),
            ('channel8',      'max'),
            ('channel8',     'IEMG'),
            ('channel8',      'SSI'),
            ('channel8',      'rms'),
            ('channel8',      'MAV'),
            ('channel8', 'variance'),
            ('channel8',       'WL'),
            ('channel8',      'ptp'),
            ('channel8',     'DAMV'),
            ('channel8',    'DASDV'),
            ('channel8',     'WAMP')],
           )

In [1360]:
X = df.drop(columns=['label','class']).values
Y = df['class'].values

C:\Users\Options\AppData\Local\Temp\ipykernel_12312\3493093677.py:1: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  X = df.drop(columns=['label','class']).values

In [1361]:
X.shape

(216, 96)

In [1362]:
Y

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4,
       5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2,
       3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6,
       1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4,
       5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2,
       3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6,
       1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4,
       5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2,
       3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6,
       1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6], dtype=int64)

In [1367]:
# Feature Selec
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

# feature selectionn
test = SelectKBest(score_func=f_classif, k=80)

Y = Y.ravel()
fit = test.fit(X, Y)

# summarize scores
np.set_printoptions(precision=1)
print(fit.scores_)

[46.9 47.4 26.5 12.7 28.1 25.5 11.8 27.3 50.1 26.3 29.1  5.6 22.8 18.2
 15.3  7.9 15.8 14.8  7.5 15.4 21.1 14.7 15.7  1.4 22.5 19.9 20.6  7.4
 20.8 21.   6.9 21.  22.8 21.9 20.9  0.4 94.4 77.4 56.6 35.3 70.7 66.5
 37.3 52.9 91.6 61.9 66.9  0.6 58.2 56.1 64.8 60.9 78.3 79.  67.4 60.2
 60.  73.6 74.3  1.8 43.7 42.4 39.7 24.2 41.9 39.8 23.9 38.6 46.  38.7
 40.1  2.8 70.  69.2 48.8 27.8 52.  48.8 27.  50.1 74.2 51.  53.5  6.5
 62.7 62.2 35.5 15.3 42.1 38.7 16.2 34.1 67.8 37.8 40.8  7.4]